# build file for scons
# this file is used to specify what to build for gem5.opt

Import('*')

SimObject('GoodbyeObject.py',
            sim_objects=['GoodbyeObject'])

Source('goodbye_object.cc')

SimObject('CustomSimObject.py', 
          sim_objects=['CustomSimObject'])



Source('custom_sim_object.cc')


# debug flag specifically for our custom sim object
DebugFlag('CustomSimObjectFlag') 