# import all the default configurations
Import('*')


SimObject('CustomSimObject.py', sim_objects=['CustomSimObject'])
# custom sim object source file
Source('custom_sim_object.cc')
# debug flag specifically for our custom sim object
DebugFlag('CustomSimObjectFlag') 